### ISSUE TITLE
can not run container

### ISSUE THREAD

**Issue by beyou923** [alibaba/accelerated-container-image#26]
Use the rpull subcommand to pull the overlaybd format image, but when I execute the following command：
    ctr run --net-host --snapshotter=overlaybd --rm -t registry.hub.docker.com/overlaybd/redis:6.2.1_obd demo
I get error :
ctr: failed to attach and mount for snapshot 8: failed to enable target for /sys/kernel/config/target/core/user_999999999/dev_8, : unknown
How to solve this problem ?

**Comment by liulanzheng** [comment]
@beyou923  the error means error occurred in the backstore. does you overlaybd backstore worked ? refer to [overlaybd](https://github.com/alibaba/overlaybd)

**Comment by beyou923** [comment]
> @beyou923 the error means error occurred in the backstore. does you overlaybd backstore worked ? refer to [overlaybd](https://github.com/alibaba/overlaybd)

run  ctr plugin ls | grep overlaybd , output:
        io.containerd.snapshotter.v1    overlaybd                -              ok 
and run   ctr snapshot  --snapshotter  overlaybd   ls  output:
KEY                                                                     PARENT                                                                  KIND      
sha256:1829a4a215c1fb0e27d05a6c9d8c6ae0455124f3e1632e9ec47b0174590f3d98 sha256:757e14492f578247120d376f52f19b6873ce75b88553c9f523c376db6c419f61 Committed 
sha256:757e14492f578247120d376f52f19b6873ce75b88553c9f523c376db6c419f61 sha256:c765bd39a999344e96d9f1b0f285d05773a28ebd7985b791094ea3b07951477b Committed 
sha256:96ba5dadca9e36ba0aec3f54b626f813f12526ad8b8e78506dca0bb631f45390 sha256:e7ad60da3cb126a7be8fe634270e9b6a5f50fa12aacadf59fcbbc59792f6b9ae Committed 
sha256:98a12eee2b158510fcb391398d60de85eaeefc7b02ca428c9883ce517a547149 sha256:a8b5fca80efae55088290f3da8110d7742de55c2a378d5ab53226a483f390e21 Committed 
sha256:a8b5fca80efae55088290f3da8110d7742de55c2a378d5ab53226a483f390e21                                                                         Committed 
sha256:c765bd39a999344e96d9f1b0f285d05773a28ebd7985b791094ea3b07951477b sha256:98a12eee2b158510fcb391398d60de85eaeefc7b02ca428c9883ce517a547149 Committed 
sha256:e7ad60da3cb126a7be8fe634270e9b6a5f50fa12aacadf59fcbbc59792f6b9ae sha256:1829a4a215c1fb0e27d05a6c9d8c6ae0455124f3e1632e9ec47b0174590f3d98 Committed 
sha256:fd84eb22532fcbe372941242bb3ebc762860b26392aaad92fd3b4342a887a66c sha256:96ba5dadca9e36ba0aec3f54b626f813f12526ad8b8e78506dca0bb631f45390 Committed

overlaybd seems to be working well.

**Comment by beyou923** [comment]
> > @beyou923 the error means error occurred in the backstore. does you overlaybd backstore worked ? refer to [overlaybd](https://github.com/alibaba/overlaybd)
> 
> run ctr plugin ls | grep overlaybd , output:
> io.containerd.snapshotter.v1 overlaybd - ok
> and run ctr snapshot --snapshotter overlaybd ls output:
> KEY PARENT KIND
> sha256:1829a4a215c1fb0e27d05a6c9d8c6ae0455124f3e1632e9ec47b0174590f3d98 sha256:757e14492f578247120d376f52f19b6873ce75b88553c9f523c376db6c419f61 Committed
> sha256:757e14492f578247120d376f52f19b6873ce75b88553c9f523c376db6c419f61 sha256:c765bd39a999344e96d9f1b0f285d05773a28ebd7985b791094ea3b07951477b Committed
> sha256:96ba5dadca9e36ba0aec3f54b626f813f12526ad8b8e78506dca0bb631f45390 sha256:e7ad60da3cb126a7be8fe634270e9b6a5f50fa12aacadf59fcbbc59792f6b9ae Committed
> sha256:98a12eee2b158510fcb391398d60de85eaeefc7b02ca428c9883ce517a547149 sha256:a8b5fca80efae55088290f3da8110d7742de55c2a378d5ab53226a483f390e21 Committed
> sha256:a8b5fca80efae55088290f3da8110d7742de55c2a378d5ab53226a483f390e21 Committed
> sha256:c765bd39a999344e96d9f1b0f285d05773a28ebd7985b791094ea3b07951477b sha256:98a12eee2b158510fcb391398d60de85eaeefc7b02ca428c9883ce517a547149 Committed
> sha256:e7ad60da3cb126a7be8fe634270e9b6a5f50fa12aacadf59fcbbc59792f6b9ae sha256:1829a4a215c1fb0e27d05a6c9d8c6ae0455124f3e1632e9ec47b0174590f3d98 Committed
> sha256:fd84eb22532fcbe372941242bb3ebc762860b26392aaad92fd3b4342a887a66c sha256:96ba5dadca9e36ba0aec3f54b626f813f12526ad8b8e78506dca0bb631f45390 Committed
> 
> overlaybd seems to be working well.

**Comment by beyou923** [comment]
overlaybd seems unable to open remote blob file, cat /var/log/overlaybd.log get the following log : 
2021/05/24 11:16:35|ERROR|th=00007FDC247B4080|zfile.cpp:699|is_zfile:failed to read file header. errno=2(No such file or directory)
2021/05/24 11:16:35|ERROR|th=00007FDC247B4080|registryfs.cpp:254|getActualUrl:Failed to get actual url [url=https://registry.hub.docker.com/v2/overlaybd/redis/blobs/][ret=404]
2021/05/24 11:16:35|ERROR|th=00007FDC247B4080|registryfs.cpp:139|GET:Failed to get actual url: [url=https://registry.hub.docker.com/v2/overlaybd/redis/blobs/]
2021/05/24 11:16:36|ERROR|th=00007FDC247B4080|registryfs.cpp:254|getActualUrl:Failed to get actual url [url=https://registry.hub.docker.com/v2/overlaybd/redis/blobs/][ret=404]
2021/05/24 11:16:36|ERROR|th=00007FDC247B4080|registryfs.cpp:139|GET:Failed to get actual url: [url=https://registry.hub.docker.com/v2/overlaybd/redis/blobs/]
2021/05/24 11:16:36|ERROR|th=00007FDC247B4080|registryfs.cpp:254|getActualUrl:Failed to get actual url [url=https://registry.hub.docker.com/v2/overlaybd/redis/blobs/][ret=404]
2021/05/24 11:16:36|ERROR|th=00007FDC247B4080|registryfs.cpp:139|GET:Failed to get actual url: [url=https://registry.hub.docker.com/v2/overlaybd/redis/blobs/]
2021/05/24 11:16:37|ERROR|th=00007FDC247B4080|registryfs.cpp:254|getActualUrl:Failed to get actual url [url=https://registry.hub.docker.com/v2/overlaybd/redis/blobs/][ret=404]
2021/05/24 11:16:37|ERROR|th=00007FDC247B4080|registryfs.cpp:139|GET:Failed to get actual url: [url=https://registry.hub.docker.com/v2/overlaybd/redis/blobs/]
2021/05/24 11:16:37|ERROR|th=00007FDC247B4080|registryfs.cpp:471|getMeta:failed to get meta from server
2021/05/24 11:16:37|ERROR|th=00007FDC247B4080|tar_zfile.cpp:349|is_tar_file:error read tar file header
2021/05/24 11:16:37|ERROR|th=00007FDC247B4080|tar_zfile.cpp:322|open_tar_zfile:open_tar_file(https://registry.hub.docker.com/v2/overlaybd/redis/blobs/) failed, 2:No such file or directory
2021/05/24 11:16:37|ERROR|th=00007FDC247B4080|cached_fs.cpp:47|open:Open source file failed errno=2(No such file or directory)
2021/05/24 11:16:37|ERROR|th=00007FDC247B4080|image_file.cpp:108|__open_ro_remote:failed to open remote file https://registry.hub.docker.com/v2/overlaybd/redis/blobs/
2021/05/24 11:16:37|ERROR|th=00007FDC247B4080|image_file.cpp:183|do_parallel_open_files:failed to open files
2021/05/24 11:16:37|ERROR|th=00007FDC293D43C0|image_file.cpp:238|open_lowers:layer index 7 open failed, exit.
2021/05/24 11:16:37|ERROR|th=00007FDC293D43C0|image_file.cpp:317|init_image_file:open lower layer failed.

**Comment by beyou923** [comment]
I can start the container normally by replacing the image (busybox), I feel it is a problem with the redis image

**Comment by beef9999** [comment]
Hi, @beyou923. Can you confirm you have cloned the latest repo code (both ACR and overlaybd). Because we have recently updated the image, and they require latest code to run.

**Comment by beyou923** [comment]
> Hi, @beyou923. Can you confirm you have cloned the latest repo code (both ACR and overlaybd). Because we have recently updated the image, and they require latest code to run.

version info :
overlaybd : overlaybd-0.2.0-1
ACR : v0.1.0

**Comment by beef9999** [comment]
@beyou923 Are you using RPM or source code?

**Comment by beyou923** [comment]
overlaybd : overlaybd-0.2.0-1.x86_64.deb
ACR : source code
my os : ubuntu-18.04.1

**Comment by beef9999** [comment]
@beyou923 It seems that we forgot to update the debian package. We will upload a new one soon, and will inform you when finished.

**Comment by beef9999** [comment]
Hi, @beyou923 . We have release the v0.3.0 debian package. Feel free to send us any feedback. https://github.com/alibaba/overlaybd/releases
