### ISSUE TITLE
Start the container in cri mode, the data in the container is abnormal

### ISSUE THREAD

**Issue by bengbeng-pp** [alibaba/accelerated-container-image#42]
The cri mode container data is abnormal, but the ctr mode is normal

Key configuration details：
![1627962766272-image](https://user-images.githubusercontent.com/53809897/127956134-8ac47854-1079-4ac5-8d46-218176599a71.png)
![3](https://user-images.githubusercontent.com/53809897/127956158-40d13af2-bd2e-49ea-915e-10496e211fd4.png)

problem：
Part of the data is missing, it is suspected that the soft chain data has this problem
![2](https://user-images.githubusercontent.com/53809897/127956178-a7dcc5f5-7133-4ebc-8ff2-b3fe6fddd653.png)

**Comment by beef9999** [comment]
Hi, @bengbeng-pp 
Sorry for late reply. Based on your description, I assume that you are using an outdated code or package. Would you update snapshotter and overlaybd to the latest and try again.
