### ISSUE TITLE
Setting up with k8s generates lot of error logs

### ISSUE THREAD

**Issue by shahzzzam** [alibaba/accelerated-container-image#49]
When I do the cri environment setup, I find a lot of failure logs in kubelet:

```
journalctl -u kubelet

....
Aug 20 02:45:20 k8s-master-17276307-0 kubelet[4845]: E0820 02:45:20.407176    4845 cri_stats_provider.go:376] Failed to get the info of the filesystem with mountpoint "/var/lib/containerd/io.containerd.snapshotter.v1.overlaybd": failed to get device for dir "/var/lib/containerd/io.containerd.snapshotter.v1.overlaybd": stat failed on /var/lib/containerd/io.containerd.snapshotter.v1.overlaybd with error: no such file or directory.
.....
```
That's probably because overlaybd snapshot system is not in `/var/lib/containerd/io.containerd.snapshotter.v1.overlaybd` but rather `/var/lib/overlaybd`

That said, the overlaybd itself did not fail. It just generates a lot of error logs on `kubelet`

**Comment by BigVan** [comment]
yep...Maybe you can change snapshotter's root by edit /etc/overlaybd-snapshotter/config.json like:
{
    "root": "/var/lib/containerd/io.containerd.snapshotter.v1.overlaybd",
    "address": "/run/overlaybd-snapshotter/overlaybd.sock"
}

and restart snapshotter:
systemctl restart overlaybd-snapshotter
